// <auto-generated />
using System;
using Flashcards.Solomonlol;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Flashcards.Solomonlol.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20260726133009_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Flashcards.Solomonlol.Model.Flashcard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StackID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StackID");

                    b.ToTable("Flashcards");
                });

            modelBuilder.Entity("Flashcards.Solomonlol.Model.SessionHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("StackID")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("StackID");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Flashcards.Solomonlol.Model.Stack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("StackName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("StackName")
                        .IsUnique();

                    b.ToTable("Stacks");
                });

            modelBuilder.Entity("Flashcards.Solomonlol.Model.Flashcard", b =>
                {
                    b.HasOne("Flashcards.Solomonlol.Model.Stack", "Stack")
                        .WithMany("Flashcards")
                        .HasForeignKey("StackID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stack");
                });

            modelBuilder.Entity("Flashcards.Solomonlol.Model.SessionHistory", b =>
                {
                    b.HasOne("Flashcards.Solomonlol.Model.Stack", "Stack")
                        .WithMany("Sessions")
                        .HasForeignKey("StackID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stack");
                });

            modelBuilder.Entity("Flashcards.Solomonlol.Model.Stack", b =>
                {
                    b.Navigation("Flashcards");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
